--- #YAML:1.0
name:                OpenVZ-BC
version:             0.01
abstract:            Perl access to OpenVZ Beancounter Data
license:             ~
author:              
    - Dusty Wilson <dev+cpan-OpenVZ-BC@megagram.com>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
